name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Verify
      run: go test -v ./...
      shell: bash
    - name: Verify race
      run: go test -v -race ./...
      shell: bash
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: Check out code
      uses: actions/checkout@v1
    - name: Download module dependencies
      env: 
         GOPROXY: "https://proxy.golang.org"
      run: go mod download
    - name: Build
      run: go build .
    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
    - name: Publish coverage
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt