name: build
on: [push, pull_request]
jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Download module dependencies
      env: 
         GOPROXY: "https://proxy.golang.org"
      run: go mod download

    - name: Build
      run: go build .

    - name: Test
      run: go test -v ./...
